config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :collections do
    resources :monuments
  end

  resources :monuments do
    resources :pictures
  end

  root to: "collections#index"

  get 'search', to: 'monuments#search'
  post 'search', to: 'monuments#search'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
    belongs_to :user
    has_many :monuments
    validates :name, presence: true, :length => { :maximum => 100 }
end

app/models/monument.rb
class Monument < ActiveRecord::Base
    acts_as_taggable
    acts_as_taggable_on :categories

    belongs_to :collection
    belongs_to :user
    has_many :pictures
    validates :name, presence: true, :length => { :maximum => 100 }
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :monument
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png", :url => "/system/pictures/photos/:hash.:extension", :hash_secret => "longSecretStringabcdefghijklmnopqrstuvwxyz"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collections
  has_many :monuments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    @collections = current_user.collections
  end

  def show
  end

  def new
    @collection = current_user.collections.new
  end

  def edit
  end

  def create
    @collection = current_user.collections.new(collection_params)

    if @collection.save
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: 'Collection was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_url, notice: 'Collection was successfully destroyed.'
  end

  private

  def set_collection
    unless @collection = current_user.collections.where(id: params[:id]).first
      flash[:alert] = 'Collection not found.'
      redirect_to action: "index"
    end
  end

  def collection_params
    params.require(:collection).permit(:name)
  end

end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  before_action :verify_and_set_collection, except: [:search]
  before_action :set_monument, only: [:show, :edit, :update, :destroy]

  def index
    @monuments = current_user.monuments.where(:collection_id => params[:collection_id])
  end

  def show
  end

  def new
    @monument = current_user.monuments.build(:collection_id => @collection.id)
  end

  def edit
  end

  def create
    @monument = current_user.monuments.create(monument_params)

    if @monument.save
      redirect_to [@collection, @monument], notice: 'Monument was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monument.update(monument_params)
      redirect_to [@collection, @monument], notice: 'Monument was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monument.destroy
    redirect_to collection_monuments_url(@collection), notice: 'Monument was successfully destroyed.'
  end

  def search
    @monuments = nil
    if request.post? && params[:keywords].present?
      if params[:search_by] == "name"
        @monuments = current_user.monuments.where("name LIKE  ?", "%#{params[:keywords]}%")
      else
        @monuments = current_user.monuments.tagged_with(params[:keywords].split(","), :any => true, :wild => true)
      end
    end
  end

  private

  def verify_and_set_collection
    unless @collection = current_user.collections.where(id: params[:collection_id]).first
      flash[:alert] = 'Collection not found.'
      redirect_to controller: "collections", action: "index"
    end
  end

  def set_monument
    unless @monument = current_user.monuments.where(id: params[:id], :collection_id => @collection.id).first
      flash[:alert] = 'Monument not found.'
      redirect_to action: "index"
    end
  end

  def monument_params
    temp_params = params.require(:monument).permit(:name, :description, :category_list)
    temp_params["collection_id"] = @collection.id
    temp_params
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :verify_and_set_monument
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = @monument.pictures
  end

  def show
  end

  def new
    @picture = @monument.pictures.build
  end

  def edit
  end

  def create
    @picture = @monument.pictures.create(picture_params)

    if @picture.save
      redirect_to [@monument, @picture], notice: 'Picture was successfully created.'
    else
      render :new
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to [@monument, @picture], notice: 'Picture was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_url, notice: 'Picture was successfully destroyed.'
  end

  private

  def verify_and_set_monument
    unless @monument = current_user.monuments.where(id: params[:monument_id]).first

      flash[:alert] = 'Monument not found.'
      redirect_to controller: "collections", action: "index"
    end
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:name, :description, :taken_on, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/monuments_helper.rb
include ActsAsTaggableOn::TagsHelper

module MonumentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<%= link_to 'Show Monuments', collection_monuments_path(@collection) %> |
<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to "Home", root_url %>
  <%= link_to "Search", search_url %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/monuments/_form.html.erb
<%= form_for([@collection, @monument]) do |f| %>
  <% if @monument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monument.errors.count, "error") %> prohibited this monument from being saved:</h2>

      <ul>
      <% @monument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :categories %><br>
    <%= f.text_field :category_list %> (comma separated)
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monuments/_list_monuments.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monuments.each do |monument| %>
      <tr>
        <td><%= monument.name %></td>
        <td><%= monument.description %></td>
        <td><%= monument.category_list %></td>
        <td><%= link_to 'Show', [monument.collection, monument] %></td>
        <td><%= link_to 'Edit', edit_collection_monument_path(monument.collection, monument) %></td>
        <td><%= link_to 'Destroy', [monument.collection, monument], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/monuments/edit.html.erb
<h1>Editing monument</h1>

<%= render 'form' %>

<%= link_to 'Show', [@monument.collection, @monument] %> |
<%= link_to 'Back', collection_monuments_path(@monument.collection) %>

app/views/monuments/index.html.erb
<h1>Listing monuments (Collection Name: <%= @collection.name %>)</h1>

<%= render 'list_monuments' %>

<br>

<%= link_to 'New Monument', new_collection_monument_path %> |
<%= link_to 'Back to Collections', collections_path %>

app/views/monuments/new.html.erb
<h1>New monument</h1>

<%= render 'form' %>

<%= link_to 'Back', collection_monuments_path(@monument.collection) %>

app/views/monuments/search.html.erb
<%= form_tag(method: "post") do %>

  Search By:
  <%= radio_button_tag(:search_by, "name", :checked => true) %>
  <%= label_tag(:search_by_name, "Name") %>
  <%= radio_button_tag(:search_by, "category") %>
  <%= label_tag(:search_by_category, "Category") %>

  <br>
  <%= label_tag(:keywords, "Search for:") %>
  <%= text_field_tag(:keywords) %>

  <br>
  <%= submit_tag("Search") %>
<% end %>

<% if @monuments %>
  <br><br>
  Found <%= @monuments.length %> results
  <br><br>
  <% if @monuments.length > 0 %>
    <%= render 'list_monuments' %>
  <% end %>
<% end %>

app/views/monuments/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @monument.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @monument.description %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @monument.category_list %>
</p>

<%= link_to 'Show Pictures', monument_pictures_path(@monument) %> |
<%= link_to 'Edit', edit_collection_monument_path(@monument.collection, @monument) %> |
<%= link_to 'Back', collection_monuments_path(@monument.collection) %>

app/views/pictures/_form.html.erb
<%= form_for([@monument, @picture], :html => { :multipart => true }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :taken_on %><br>
    <%= f.date_select :taken_on %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', [@picture.monument, @picture] %> |
<%= link_to 'Back', monument_pictures_path(@picture.monument) %>

app/views/pictures/index.html.erb
<h1>Listing pictures (Monument Name: <%= @monument.name %>)</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Taken on</th>
      <th>Photo Thumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.description %></td>
        <td><%= picture.taken_on %></td>
        <td><%= image_tag picture.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', [picture.monument, picture] %></td>
        <td><%= link_to 'Edit', edit_monument_picture_path(picture.monument, picture) %></td>
        <td><%= link_to 'Destroy', [picture.monument, picture], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_monument_picture_path(@monument) %> |
<%= link_to 'Back to Monuments', collection_monuments_path(@monument.collection) %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', new_monument_picture_path(@monument) %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Taken on:</strong>
  <%= @picture.taken_on %>
</p>

<%= image_tag @picture.photo.url %><br>
<%= image_tag @picture.photo.url(:medium) %><br>
<%= image_tag @picture.photo.url(:thumb) %><br>

<%= link_to 'Edit', edit_monument_picture_path(@picture.monument, @picture) %> |
<%= link_to 'Back', monument_pictures_path(@picture.monument) %>